name: Update Calendar

on:
  schedule:
    - cron: '0 20 * * *' # 每天自動跑一次 (北京時間凌晨 4:00)
  workflow_dispatch: # 允許手動點擊執行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 給予寫入權限以便更新檔案
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # 這裡只保留 requests，因為農曆我們已經寫死在代碼裡了，這樣跑得最快最穩
        run: pip install requests

      - name: Run script
        run: python main.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add calendar.ics
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update calendar" && git push)
